apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    environment: dev
    app: frontend
spec:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http-web-svc
---
apiVersion: v1
kind: service
metadata:
  name: nginx-service
spec:
  selector:
    environment: dev
    app: frontend
  ports:
  - name: nginx-service
    protocol: TCP
    port: 80
    targetPort: http-web-svc