apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    environment: dev
    app: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    environment: dev
    app: frontend
  ports:  
  - name: service-port
    protocol: tcp
    port: 80
    targetPort: http-web-svc