apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: Dev
    app: front-end
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    environment: Dev
    app: front-end
  ports:
    - name: name-of-service-port
      port: 80
      protocol: TCP
      targetPort: http-web-svc
