apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    environment: dev
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:  
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    environment: dev
    tier: frontend
  ports:
    - name: service-port
      port: 80
      protocol: TCP
      targetPort: http-web-svc
      NodePort: 30000