apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: dev
    tier: frontend
spec:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer 
  selector:
    environment: dev
    tier: frontend
  ports:
    - name: loadbalancer-port
      port: 80
      protocol: TCP
      targetPort: http-web-svc