apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    environment: dev
    tier: frontend
spec:
  template:
    metadata:
      labels:
        environment: dev
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
  replicas: 3
  selector:
    matchlabels: 
     environment: dev
     tier: frontend 