apiVersion: v1
kind: ReplicaSet
metadata:
  name: frontend-replica
  labels:
    environment: dev
    tier: frontend
spec:
  replicas: 3
  selector:
    environment: dev
    tier: frontend
  template:
    metadata:
      environment: dev
      tier: frontend
    spec:
      containers:
       - name: nginx
         image: nginx:latest
  