apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels: 
    env: prod
  annotations: 
    com.environment: prod
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
      - containerPort: 80