apiVersion: v1
kind: Pod
metadata:
  name: resources
  label: 
    name: resources-example
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "210Mi"
