apiVersion: v1
kind: Pod
metadata: 
  name: env-example
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      env: 
      - name: test1
        value: "hello there"

      - name: test2
        value: "How are you?" 
