apiVersion: v1
kind: Pod
metadata:
  name: environment_test
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env: 
    - name: Demo_Greeting
      value: "hello world"
    - name: Demo_Farewell
      value: "bye bye"