apiVersion: v1
kind: Pod
metadata:
  name: config
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: always
      env: 
      - name: COURSE
        valueFrom: 
          configMapKeyRef: 
            name: course-config
            key: COURSE