apiVersion: v1
kind: Pod
metadata:
  name: configmap-ref-example
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: test2
          valueFrom:
            configMapKeyRef:
              name: configmap-ref
              key: test2
