apiVersion: v1
kind: Pod
metadata:
  name: config
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: Always
      env: 
      - name: COURSE
        valueFrom: 
          configMapKeyRef: 
            name: course-config
            key: COURSE
      - name: TRAINER
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: TRAINER
            