apiVersion: v1
kind: Pod
metadata:
  name: config
spec:
  containers:
    - name: nginx
      image: nginx
      env: 
      - name: COURSE
        valuefrom: 
          configMapKeyRef: 
            name: course-config
            key: COURSE