apiVersion: v1
kind: Secret
metadata:
  name: secret 
data:
  username: bmF2ZWVuCg== #echo "naveen" | base64
  password: bmF2ZWVuCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
      name: secret 